### ISSUE TITLE
Top level selector

### ISSUE THREAD

**Issue by iefserge** [pazams/postcss-scopify#10]
Thank you, this module is awesome!

Wrapping selectors into class scope works well, but I haven't found a way to add styles at the top-level, i.e. to the scope directly.

Would it be a good idea to add support for a top-level `&` selector that resolves directly to the scope?

like

``` css
& {
  color: red;
}
.selector {
  color: green;
}
```

transforms into:

``` css
.scope {
  color: red;
}
.scope .selector {
  color: green;
}
```
